setwd("C:/Users/Manuel Rossi/Desktop/r bachelor")
library(boot)
library(mosaic)
data <- read_excel("Book1.xlsx")
attach(data)
n <- length(All)
mean(All)
ste <- sd(All);ste
hist(All, freq = FALSE, xlab="Profits",main = "Distribution of Profits")

set.seed(123)
bs1 <- sample(All,97,replace = TRUE)
bs <- replicate(10000,mean(sample(All,97,replace = TRUE)))
bs2 <- replicate(10000,var(sample(All,97,replace = TRUE)))
mean(bs)
mean(bs2)
hist(bs, freq = FALSE,  xlab="Profits", main = "Distribution of Profits", ylim = c(0, 50))
hist(bs,  xlab="Profits", main = "Distribution of Profits")
abline(v=-0.002553452, col="blue")
abline(v=0.03138174, col="blue")
curve(dnorm(x,mean(bs),sd(bs)), add=TRUE, col = "red")
confint(bs, level = 0.95, method = "quantile")

boxplot(BTC, ETC, BNB, XRP, ADA, DOGE, WETH, names=c("BTC","ETC", "BNB", "XRP", "ADA", "DOGE", "WETH"))
x <- c(length(BTC),length(ETC), length(BNB))

hist(bs2, freq = FALSE,  xlab="Varianz", main = "Distribution of Variance", ylim = c(0, 500))
curve(dnorm(x,mean(bs2),sd(bs2)), add=TRUE, col = "red")
confint(bs2, level = 0.95, method = "quantile")
abline(v=0.005492371, col="blue")
abline(v=0.009181614, col="blue")
mean(bs2)
